In [ ]:
import numpy as np

In [ ]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

In [ ]:
np.add(n1,n2)

array([5, 7, 9])

In [ ]:
n1 + n2

array([5, 7, 9])

In [ ]:
n1 - n2

array([-3, -3, -3])

In [ ]:
n1 * n2

array([ 4, 10, 18])

In [ ]:
n1 ** n2

array([  1,  32, 729])

In [ ]:
n1/n2

array([0.25, 0.4 , 0.5 ])

In [ ]:
n1 < n2

array([ True,  True,  True])

In [ ]:
n3 = np.array([[1,2],[3,4]])
n4 = np.array([[5,6],[7,8]])

In [ ]:
n3 + n4

array([[ 6,  8],
       [10, 12]])

In [ ]:
n3 & n4

array([[1, 2],
       [3, 0]])

In [ ]:
n3 | n4

array([[ 5,  6],
       [ 7, 12]])

In [ ]:
n3 * 10

array([[10, 20],
       [30, 40]])

In [ ]:
n3 = np.array([[1,2],[3,4]])
n4 = np.array([[5,6],[7,8]])

In [ ]:
np.matmul(n3,n4)

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(n3,n4)

array([[19, 22],
       [43, 50]])

In [ ]:
np.sqrt(n3)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
n3 ** 0.5

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
n3

array([[1, 2],
       [3, 4]])

In [ ]:
n3.flatten('C')

array([1, 2, 3, 4])

In [ ]:
n3.flatten('F')

array([1, 3, 2, 4])

In [ ]:
day1 = np.datetime64('2022-01-01')
print(day1)

2022-01-01


In [ ]:
type(day1)

numpy.datetime64

In [ ]:
day2 = np.datetime64('2022-04-01')
print(day2)

2022-04-01


In [ ]:
days = day2 - day1
print(days)

90 days


In [ ]:
print(np.datetime64('2022-04-10') - np.datetime64('2022-04-01'))

9 days


In [ ]:
print(np.datetime64('2022-04-01') + np.timedelta64(6,'D'))

2022-04-07


In [ ]:
print(np.datetime64('Today'))

2022-04-10


In [ ]:
n3

array([[1, 2],
       [3, 4]])

In [ ]:
n4

array([[5, 6],
       [7, 8]])

In [ ]:
np.hstack([n3,n4])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack([n3,n4])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.dstack([n3,n4])

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [ ]:
np.column_stack([n3,n4])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.row_stack([n3,n4])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.append(n3,n4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.append(n3,n4,axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.append(n3,n4,axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.append(n3,n4,axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((n3,n4),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((n3,n4),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
n5 = np.arange(1,19).reshape(6,3)

In [ ]:
n5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.array_split(n5,len(n5))

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [ ]:
np.hsplit(n5,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:
np.vsplit(n5,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [ ]:
# have to check
# np.hsplit(n5,np.array([1,1]))